In [1]:
# Load libraries
import pandas as pd
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression as LogReg
import random
from sklearn.cross_validation import KFold
from sklearn.linear_model import LinearRegression as LinReg

In [7]:
# Read in the separate files
data_17 = pd.read_csv("../data/pbp_2017.csv")
data_16 = pd.read_csv("../data/pbp_2016.csv")
data_15 = pd.read_csv("../data/pbp_2015.csv")
data_14 = pd.read_csv("../data/pbp_2014.csv")
data_13 = pd.read_csv("../data/pbp_2013.csv")
data_12 = pd.read_csv("../data/pbp_2012.csv")
data_11 = pd.read_csv("../data/pbp_2011.csv")
data_10 = pd.read_csv("../data/pbp_2010.csv")

frames = [data_17, data_16, data_15, data_14, data_13, data_12, data_11, data_10]
data = pd.concat(frames)

/Users/curtishsu/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/curtishsu/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [70]:
# for each data frame get the total number of 
## offensive stats
# get records
# passing yards check
# rushing yards check
# touchdowns
# interceptions
# penalty yards

def getPassingYards(df):
    
    #init
    d_offense = {}
    d_defense = {}    
    d_offense['NE'] = 0
    d_offense['DET'] = 0
    d_offense['CLE'] = 0
    d_defense['NE'] = 0
    d_defense['DET'] = 0
    d_defense['CLE'] = 0
    
    # iterate through rows
    # if posteam in d_offense
    # if playtype = Pass
    # add to value
    
    for index, row in df.iterrows():
        if row.posteam in d_offense:
            if row.PlayType == "Pass":
                d_offense[row.posteam] += row['Yards.Gained']
                
        if row.DefensiveTeam in d_defense:
            if row.PlayType =="Pass":
                d_defense[row.DefensiveTeam] += row['Yards.Gained']
    return d_offense, d_defense


def getRushingYards(df):
    
    #init
    d_offense = {}
    d_defense = {}    
    d_offense['NE'] = 0
    d_offense['DET'] = 0
    d_offense['CLE'] = 0
    d_defense['NE'] = 0
    d_defense['DET'] = 0
    d_defense['CLE'] = 0
    
    # iterate through rows
    # if posteam in d_offense
    # if playtype = Pass
    # add to value
    
    for index, row in df.iterrows():
        if row.posteam in d_offense:
            if row.PlayType == "Run":
                d_offense[row.posteam] += row['Yards.Gained']
                
        if row.DefensiveTeam in d_defense:
            if row.PlayType =="Run":
                d_defense[row.DefensiveTeam] += row['Yards.Gained']
    return d_offense, d_defense

def getTouchdowns(df):
    
    #init
    d_offense = {}
    d_defense = {}    
    d_offense['NE'] = 0
    d_offense['DET'] = 0
    d_offense['CLE'] = 0
    d_defense['NE'] = 0
    d_defense['DET'] = 0
    d_defense['CLE'] = 0
    
    # iterate through rows
    # if posteam in d_offense
    # if playtype = Pass
    # add to value
    
    for index, row in df.iterrows():
        if row.posteam in d_offense:
            if row.Touchdown == 1:
                d_offense[row.posteam] += 1
                
        if row.DefensiveTeam in d_defense:
            if row.Touchdown == 1:
                d_defense[row.DefensiveTeam] += 1
    return d_offense, d_defense


def getInterception(df):
    
    #init
    d_offense = {}
    d_defense = {}    
    d_offense['NE'] = 0
    d_offense['DET'] = 0
    d_offense['CLE'] = 0
    d_defense['NE'] = 0
    d_defense['DET'] = 0
    d_defense['CLE'] = 0
    
    # iterate through rows
    # if posteam in d_offense
    # if playtype = Pass
    # add to value
    
    for index, row in df.iterrows():
        if row.posteam in d_offense:
            if row.InterceptionThrown == 1:
                d_offense[row.posteam] += 1
                
        if row.DefensiveTeam in d_defense:
            if row.InterceptionThrown == 1:
                d_defense[row.DefensiveTeam] += 1
    return d_offense, d_defense
    
    
def getWins(df):
    #init
    d_offense = {}
    d_offense['NE'] = 0
    d_offense['DET'] = 0
    d_offense['CLE'] = 0
    for index, row in df.iterrows():
        if row.desc == "END GAME":
            if row.posteam in d_offense:
                print row.posteam
                if row.PosTeamScore > row.DefTeamScore:
                    d_offense[row.posteam] += 1

            if row.DefensiveTeam in d_offense:
                print row.DefensiveTeam
                if row.DefTeamScore > row.PosTeamScore:
                    d_offense[row.DefensiveTeam] += 1
    return d_offense

In [50]:
def concatStats(df):
    data = {'Team': ['CLE',"DET","NE"]}
    new_df = pd.DataFrame(data)
    x, y =  getPassingYards(df)
    new_df['OffensivePassingYards'] = x.values()
    new_df['DefensivePassingYards'] = y.values()
    x, y =  getRushingYards(df)
    new_df['OffensiveRushingYards'] = x.values()
    new_df['DefensiveRushingYards'] = y.values()
    x, y =  getTouchdowns(df)
    new_df['OffensiveTouchdowns'] = x.values()
    new_df['TouchdownsScoredAgainst'] = y.values()
    x, y =  getInterception(df)
    new_df['Interceptions'] = x.values()
    new_df['Picks'] = y.values()
    new_df['Year'] = df.iloc[0:3].Season.values
    return new_df

In [78]:
ls = []
for i in range(0,8):
    year = 2010 + i
    txt = "../data/pbp_" + str(year) + ".csv"
    df = pd.read_csv(txt)
    x = concatStats(df)
    ls.append(x)
    
data = pd.concat(ls)

In [80]:
wins = []
browns = [5,4,5,4,7,3,1,0]
lions = [6,10,4,7,11,7,9,9]
pats = [14,13,12,12,12,12,14,13]
for i in range(0,8):
    wins.append(browns[i])
    wins.append(lions[i])
    wins.append(pats[i])
    
data['wins'] = wins

In [81]:
data

,Team,OffensivePassingYards,DefensivePassingYards,OffensiveRushingYards,DefensiveRushingYards,OffensiveTouchdowns,TouchdownsScoredAgainst,Interceptions,Picks,Year,wins
0,CLE,3253,3732,1601,2104,29,36,19,19,2010,5
1,DET,4026,3842,1623,2045,42,45,16,16,2010,6
2,NE,3768,3997,1877,1654,54,39,5,26,2010,14
0,CLE,3317,3195,1554,2382,24,32,16,10,2011,4
1,DET,5387,4453,1578,2112,58,47,16,21,2011,10
2,NE,5188,5021,1778,1888,59,45,13,26,2011,13
0,CLE,3343,3818,1576,1811,31,42,19,16,2012,5
1,DET,4842,3712,1564,1859,46,41,22,13,2012,4
2,NE,4504,4245,1978,1569,55,40,11,17,2012,12
0,CLE,4378,3735,1396,1799,34,47,20,14,2013,4
1,DET,4506,4161,1752,1454,51,38,19,14,2013,7
2,NE,4395,4156,2092,2153,49,40,11,19,2013,12
0,CLE,3725,3906,1713,2284,31,38,18,21,2014,7
1,DET,4307,4068,1440,1126,35,33,12,22,2014,11
2,NE,4347,4139,1761,1706,50,37,9,18,2014,12
0,CLE,4191,4235,1547,2069,29,50,13,12,2015,3
1,DET,4483,4147,1360,1797,41,50,17,10,2015,7
2,NE,4849,4214,1423,1600,55,35,9,13,2015,12
0,CLE,3747,4194,1721,2296,30,56,14,10,2016,1
1,DET,4378,4146,1324,1748,35,44,12,11,2016,9
2,NE,4450,4021,1894,1411,52,27,2,14,2016,14
0,CLE,3578,3884,1720,1607,32,44,29,8,2017,0
1,DET,4511,4111,1255,1876,46,48,13,21,2017,9
2,NE,4597,4345,1919,1861,53,34,11,12,2017,13

In [82]:
data.to_csv("MajorStats1.csv")